export const REQUEST_USERS = 'REQUEST_USERS';
export const LOGIN_USER = 'LOGIN_USER';

export const REQUEST_PROJECTS_ALL = 'REQUEST_PROJECTS_ALL';
export const REQUEST_PROJECTS_OWNED = 'REQUEST_PROJECTS_OWNED';
export const REQUEST_PROJECTS_BACKED = 'REQUEST_PROJECTS_BACKED';
export const REQUEST_BACK_PROJECTS = 'REQUEST_BACK_PROJECTS';
export const REQUEST_CREATE_PROJECTS = 'REQUEST_CREATE_PROJECTS';

export const API_ENDPOINT = '//localhost:8000';
